// Charger votre JSON
const data = [
  {
    option: "permis-construire",
    isStepThreeChecked: true,
    isArchitectNeeded: true,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 3,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 2,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    clientFirstName: "Jean",
    clientLastName: "Dupont",
    clientPhone: "+33612345678",
    clientEmail: "jean.dupont@email.fr",
    pdfUrl: "/pdf/devis-001.pdf",
  },
  {
    option: "permis-construire",
    isStepThreeChecked: true,
    isArchitectNeeded: false,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 5,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 4,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    clientFirstName: "Marie",
    clientLastName: "Martin",
    clientPhone: "+33698765432",
    clientEmail: "marie.martin@gmail.com",
    pdfUrl: "/pdf/devis-001(1).pdf",
  },
  {
    option: "permis-construire",
    isStepThreeChecked: true,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 1,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 3,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    clientFirstName: "Pierre",
    clientLastName: "Dubois",
    clientPhone: "+33645678901",
    clientEmail: "p.dubois@outlook.fr",
    pdfUrl: "/pdf/devis-001(2).pdf",
  },
  {
    option: "declaration-prealable",
    isStepThreeChecked: true,
    isArchitectNeeded: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 4,
    cerfaFilling: true,
    pluVerification: true,
    expressDelivery: true,
    displayPanel: true,
    doesNeedPlan: true,
    neededPlans: ["Plan de masse", "Plan de façade", "Plan en coupe"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 2,
    shouldMake3dRender: true,
    renderCount3d: 3,
    render3D: true,
    clientFirstName: "Sophie",
    clientLastName: "Bernard",
    clientPhone: "+33623456789",
    clientEmail: "sophie.bernard@yahoo.fr",
    pdfUrl: "/pdf/devis-001(3).pdf",
  },
  {
    option: "declaration-prealable",
    isStepThreeChecked: true,
    isArchitectNeeded: false,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 2,
    cerfaFilling: true,
    pluVerification: true,
    expressDelivery: true,
    displayPanel: true,
    doesNeedPlan: true,
    neededPlans: ["Plan de situation", "Plan de toiture"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 1,
    shouldMake3dRender: true,
    renderCount3d: 5,
    render3D: true,
    clientFirstName: "Luc",
    clientLastName: "Lefebvre",
    clientPhone: "+33634567890",
    clientEmail: "luc.lefebvre@laposte.net",
    pdfUrl: "/pdf/devis-001(4).pdf",
  },
  {
    option: "declaration-prealable",
    isStepThreeChecked: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 3,
    cerfaFilling: true,
    pluVerification: true,
    expressDelivery: true,
    displayPanel: true,
    doesNeedPlan: true,
    neededPlans: ["Plan des façades", "Plan d'insertion"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 4,
    shouldMake3dRender: true,
    renderCount3d: 2,
    render3D: true,
    clientFirstName: "Claire",
    clientLastName: "Moreau",
    clientPhone: "+33656789012",
    clientEmail: "claire.moreau@free.fr",
    pdfUrl: "/pdf/devis-001(5).pdf",
  },
  {
    option: "dossier-erp",
    isStepThreeChecked: true,
    isArchitectNeeded: true,
    cerfaFilling: true,
    pluVerification: true,
    expressDelivery: true,
    displayPanel: true,
    doesNeedPlan: true,
    neededPlans: ["Plan d'évacuation", "Plan de sécurité incendie"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 3,
    clientFirstName: "Thomas",
    clientLastName: "Petit",
    clientPhone: "+33667890123",
    clientEmail: "thomas.petit@orange.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "dossier-erp",
    isStepThreeChecked: true,
    isArchitectNeeded: false,
    cerfaFilling: true,
    pluVerification: true,
    expressDelivery: true,
    displayPanel: true,
    doesNeedPlan: true,
    neededPlans: ["Plan de masse ERP", "Plan d'accessibilité"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 5,
    clientFirstName: "Amélie",
    clientLastName: "Roux",
    clientPhone: "+33678901234",
    clientEmail: "amelie.roux@hotmail.com",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "dossier-erp",
    isStepThreeChecked: true,
    cerfaFilling: true,
    pluVerification: true,
    expressDelivery: true,
    displayPanel: true,
    doesNeedPlan: true,
    neededPlans: ["Plan technique", "Plan de circulation"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 1,
    clientFirstName: "Nicolas",
    clientLastName: "Garnier",
    clientPhone: "+33689012345",
    clientEmail: "n.garnier@gmail.com",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "certificat-urbanisme",
    isStepThreeChecked: true,
    isArchitectNeeded: true,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 2,
    cerfaFilling: true,
    pluVerification: true,
    expressDelivery: true,
    clientFirstName: "Isabelle",
    clientLastName: "David",
    clientPhone: "+33690123456",
    clientEmail: "isabelle.david@sfr.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "certificat-urbanisme",
    isStepThreeChecked: true,
    isArchitectNeeded: false,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 4,
    cerfaFilling: true,
    pluVerification: true,
    expressDelivery: true,
    clientFirstName: "Laurent",
    clientLastName: "Simon",
    clientPhone: "+33601234567",
    clientEmail: "laurent.simon@wanadoo.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "certificat-urbanisme",
    isStepThreeChecked: true,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 5,
    cerfaFilling: true,
    pluVerification: true,
    expressDelivery: true,
    clientFirstName: "Céline",
    clientLastName: "Laurent",
    clientPhone: "+33612345098",
    clientEmail: "celine.laurent@bbox.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "plan-unite",
    isStepThreeChecked: true,
    isArchitectNeeded: true,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 3,
    doesNeedPlan: true,
    neededPlans: ["Plan RDC", "Plan étage", "Plan 3D"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 2,
    shouldMake3dRender: true,
    renderCount3d: 4,
    render3D: true,
    expressDelivery: true,
    clientFirstName: "Julien",
    clientLastName: "Blanc",
    clientPhone: "+33623456098",
    clientEmail: "julien.blanc@live.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "plan-unite",
    isStepThreeChecked: true,
    isArchitectNeeded: false,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 1,
    doesNeedPlan: true,
    neededPlans: ["Plan architectural", "Plan technique"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 3,
    shouldMake3dRender: true,
    renderCount3d: 1,
    render3D: true,
    expressDelivery: true,
    clientFirstName: "Nathalie",
    clientLastName: "Girard",
    clientPhone: "+33634567098",
    clientEmail: "nathalie.girard@numericable.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "plan-unite",
    isStepThreeChecked: true,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 5,
    doesNeedPlan: true,
    neededPlans: ["Plan de distribution"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 5,
    shouldMake3dRender: true,
    renderCount3d: 2,
    render3D: true,
    expressDelivery: true,
    clientFirstName: "Vincent",
    clientLastName: "Morel",
    clientPhone: "+33645678098",
    clientEmail: "vincent.morel@club-internet.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "etude-re2020",
    isStepThreeChecked: true,
    isArchitectNeeded: true,
    bbioStudy: true,
    expressDelivery: true,
    clientFirstName: "Sandrine",
    clientLastName: "Fontaine",
    clientPhone: "+33656789098",
    clientEmail: "sandrine.fontaine@gmail.com",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "etude-re2020",
    isStepThreeChecked: true,
    isArchitectNeeded: false,
    bbioStudy: true,
    expressDelivery: true,
    clientFirstName: "Olivier",
    clientLastName: "Chevalier",
    clientPhone: "+33667890098",
    clientEmail: "olivier.chevalier@yahoo.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "etude-re2020",
    isStepThreeChecked: true,
    bbioStudy: true,
    expressDelivery: true,
    clientFirstName: "Émilie",
    clientLastName: "Gauthier",
    clientPhone: "+33678901098",
    clientEmail: "emilie.gauthier@outlook.com",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "etude-sismique",
    isStepThreeChecked: true,
    isArchitectNeeded: true,
    seismicStudy: true,
    expressDelivery: true,
    clientFirstName: "Maxime",
    clientLastName: "Perrin",
    clientPhone: "+33689012098",
    clientEmail: "maxime.perrin@laposte.net",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "etude-sismique",
    isStepThreeChecked: true,
    isArchitectNeeded: false,
    seismicStudy: true,
    expressDelivery: true,
    clientFirstName: "Valérie",
    clientLastName: "Rousseau",
    clientPhone: "+33690123098",
    clientEmail: "valerie.rousseau@free.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "etude-sismique",
    isStepThreeChecked: true,
    seismicStudy: true,
    expressDelivery: true,
    clientFirstName: "Christophe",
    clientLastName: "Mercier",
    clientPhone: "+33601234098",
    clientEmail: "christophe.mercier@orange.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "aide-conception",
    isStepThreeChecked: true,
    isArchitectNeeded: true,
    doesNeedPlan: true,
    neededPlans: ["Plan conception", "Plan esquisse"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 4,
    shouldMake3dRender: true,
    renderCount3d: 3,
    render3D: true,
    expressDelivery: true,
    clientFirstName: "Stéphanie",
    clientLastName: "Lambert",
    clientPhone: "+33612345987",
    clientEmail: "stephanie.lambert@hotmail.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "aide-conception",
    isStepThreeChecked: true,
    isArchitectNeeded: false,
    doesNeedPlan: true,
    neededPlans: ["Plan avant-projet", "Plan détaillé"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 1,
    shouldMake3dRender: true,
    renderCount3d: 5,
    render3D: true,
    expressDelivery: true,
    clientFirstName: "Frédéric",
    clientLastName: "Bonnet",
    clientPhone: "+33623456987",
    clientEmail: "frederic.bonnet@sfr.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "aide-conception",
    isStepThreeChecked: true,
    doesNeedPlan: true,
    neededPlans: ["Plan préliminaire"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 2,
    shouldMake3dRender: true,
    renderCount3d: 4,
    render3D: true,
    expressDelivery: true,
    clientFirstName: "Caroline",
    clientLastName: "Fournier",
    clientPhone: "+33634567987",
    clientEmail: "caroline.fournier@wanadoo.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "permis-construire",
    isStepThreeChecked: true,
    isArchitectNeeded: true,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 3,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 2,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 4,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 2,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 5,
    doesNeedPlan: true,
    neededPlans: ["Plan de masse", "Plan de façade", "Plan en coupe"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 3,
    shouldMake3dRender: true,
    renderCount3d: 4,
    render3D: true,
    clientFirstName: "Jean",
    clientLastName: "Dupont",
    clientPhone: "+33612345678",
    clientEmail: "jean.dupont@email.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "permis-construire",
    isStepThreeChecked: true,
    isArchitectNeeded: false,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 5,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 4,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 1,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 3,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 2,
    doesNeedPlan: true,
    neededPlans: ["Plan de situation", "Plan de toiture", "Plan des façades"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 5,
    shouldMake3dRender: true,
    renderCount3d: 1,
    render3D: true,
    clientFirstName: "Marie",
    clientLastName: "Martin",
    clientPhone: "+33698765432",
    clientEmail: "marie.martin@gmail.com",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "permis-construire",
    isStepThreeChecked: true,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 1,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 3,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 5,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 4,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 3,
    doesNeedPlan: true,
    neededPlans: ["Plan d'insertion", "Plan en coupe", "Plan de masse"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 2,
    shouldMake3dRender: true,
    renderCount3d: 3,
    render3D: true,
    clientFirstName: "Pierre",
    clientLastName: "Dubois",
    clientPhone: "+33645678901",
    clientEmail: "p.dubois@outlook.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "declaration-prealable",
    isStepThreeChecked: true,
    isArchitectNeeded: true,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 4,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 1,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 2,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 5,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 1,
    doesNeedPlan: true,
    neededPlans: ["Plan de façade", "Plan de situation"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 4,
    shouldMake3dRender: true,
    renderCount3d: 5,
    render3D: true,
    clientFirstName: "Sophie",
    clientLastName: "Bernard",
    clientPhone: "+33623456789",
    clientEmail: "sophie.bernard@yahoo.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "declaration-prealable",
    isStepThreeChecked: true,
    isArchitectNeeded: false,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 2,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 5,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 3,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 1,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 4,
    doesNeedPlan: true,
    neededPlans: ["Plan de toiture", "Plan en coupe", "Plan d'insertion"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 1,
    shouldMake3dRender: true,
    renderCount3d: 2,
    render3D: true,
    clientFirstName: "Luc",
    clientLastName: "Lefebvre",
    clientPhone: "+33634567890",
    clientEmail: "luc.lefebvre@laposte.net",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "declaration-prealable",
    isStepThreeChecked: true,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 3,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 2,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 4,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 2,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 5,
    doesNeedPlan: true,
    neededPlans: ["Plan des façades", "Plan de masse"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 3,
    shouldMake3dRender: true,
    renderCount3d: 4,
    render3D: true,
    clientFirstName: "Claire",
    clientLastName: "Moreau",
    clientPhone: "+33656789012",
    clientEmail: "claire.moreau@free.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "dossier-erp",
    isStepThreeChecked: true,
    isArchitectNeeded: true,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 5,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 4,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 1,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 3,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 2,
    doesNeedPlan: true,
    neededPlans: [
      "Plan d'évacuation",
      "Plan de sécurité incendie",
      "Plan d'accessibilité",
    ],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 5,
    shouldMake3dRender: true,
    renderCount3d: 1,
    render3D: true,
    clientFirstName: "Thomas",
    clientLastName: "Petit",
    clientPhone: "+33667890123",
    clientEmail: "thomas.petit@orange.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "dossier-erp",
    isStepThreeChecked: true,
    isArchitectNeeded: false,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 1,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 3,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 5,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 4,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 3,
    doesNeedPlan: true,
    neededPlans: ["Plan de masse ERP", "Plan technique", "Plan de circulation"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 2,
    shouldMake3dRender: true,
    renderCount3d: 4,
    render3D: true,
    clientFirstName: "Amélie",
    clientLastName: "Roux",
    clientPhone: "+33678901234",
    clientEmail: "amelie.roux@hotmail.com",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "dossier-erp",
    isStepThreeChecked: true,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 4,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 1,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 2,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 5,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 1,
    doesNeedPlan: true,
    neededPlans: ["Plan de sécurité", "Plan des issues"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 4,
    shouldMake3dRender: true,
    renderCount3d: 3,
    render3D: true,
    clientFirstName: "Nicolas",
    clientLastName: "Garnier",
    clientPhone: "+33689012345",
    clientEmail: "n.garnier@gmail.com",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "certificat-urbanisme",
    isStepThreeChecked: true,
    isArchitectNeeded: true,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 2,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 5,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 3,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 1,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 4,
    doesNeedPlan: true,
    neededPlans: ["Plan cadastral", "Plan de situation"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 2,
    shouldMake3dRender: true,
    renderCount3d: 5,
    render3D: true,
    clientFirstName: "Isabelle",
    clientLastName: "David",
    clientPhone: "+33690123456",
    clientEmail: "isabelle.david@sfr.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "certificat-urbanisme",
    isStepThreeChecked: true,
    isArchitectNeeded: false,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 3,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 4,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 5,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 2,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 1,
    doesNeedPlan: true,
    neededPlans: ["Plan de zonage", "Plan local d'urbanisme"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 3,
    shouldMake3dRender: true,
    renderCount3d: 1,
    render3D: true,
    clientFirstName: "Laurent",
    clientLastName: "Simon",
    clientPhone: "+33601234567",
    clientEmail: "laurent.simon@wanadoo.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "certificat-urbanisme",
    isStepThreeChecked: true,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 5,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 1,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 4,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 3,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 2,
    doesNeedPlan: true,
    neededPlans: ["Plan de terrain", "Plan réglementaire"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 5,
    shouldMake3dRender: true,
    renderCount3d: 4,
    render3D: true,
    clientFirstName: "Céline",
    clientLastName: "Laurent",
    clientPhone: "+33612345098",
    clientEmail: "celine.laurent@bbox.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "plan-unite",
    isStepThreeChecked: true,
    isArchitectNeeded: true,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 1,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 2,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 1,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 5,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 3,
    doesNeedPlan: true,
    neededPlans: ["Plan RDC", "Plan étage", "Plan 3D"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 4,
    shouldMake3dRender: true,
    renderCount3d: 2,
    render3D: true,
    clientFirstName: "Julien",
    clientLastName: "Blanc",
    clientPhone: "+33623456098",
    clientEmail: "julien.blanc@live.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "plan-unite",
    isStepThreeChecked: true,
    isArchitectNeeded: false,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 4,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 3,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 2,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 4,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 5,
    doesNeedPlan: true,
    neededPlans: [
      "Plan architectural",
      "Plan technique",
      "Plan de distribution",
    ],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 1,
    shouldMake3dRender: true,
    renderCount3d: 3,
    render3D: true,
    clientFirstName: "Nathalie",
    clientLastName: "Girard",
    clientPhone: "+33634567098",
    clientEmail: "nathalie.girard@numericable.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "plan-unite",
    isStepThreeChecked: true,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 2,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 5,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 3,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 1,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 4,
    doesNeedPlan: true,
    neededPlans: ["Plan de coupe", "Plan de façade"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 2,
    shouldMake3dRender: true,
    renderCount3d: 5,
    render3D: true,
    clientFirstName: "Vincent",
    clientLastName: "Morel",
    clientPhone: "+33645678098",
    clientEmail: "vincent.morel@club-internet.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "etude-re2020",
    isStepThreeChecked: true,
    isArchitectNeeded: true,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 3,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 4,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 5,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 2,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 1,
    doesNeedPlan: true,
    neededPlans: ["Plan thermique", "Plan énergétique"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 3,
    shouldMake3dRender: true,
    renderCount3d: 4,
    render3D: true,
    clientFirstName: "Sandrine",
    clientLastName: "Fontaine",
    clientPhone: "+33656789098",
    clientEmail: "sandrine.fontaine@gmail.com",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "etude-re2020",
    isStepThreeChecked: true,
    isArchitectNeeded: false,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 5,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 1,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 4,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 3,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 2,
    doesNeedPlan: true,
    neededPlans: ["Plan bioclimatique", "Plan RT2020"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 5,
    shouldMake3dRender: true,
    renderCount3d: 1,
    render3D: true,
    clientFirstName: "Olivier",
    clientLastName: "Chevalier",
    clientPhone: "+33667890098",
    clientEmail: "olivier.chevalier@yahoo.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "etude-re2020",
    isStepThreeChecked: true,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 1,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 2,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 1,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 5,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 3,
    doesNeedPlan: true,
    neededPlans: ["Plan conformité RE2020"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 4,
    shouldMake3dRender: true,
    renderCount3d: 2,
    render3D: true,
    clientFirstName: "Émilie",
    clientLastName: "Gauthier",
    clientPhone: "+33678901098",
    clientEmail: "emilie.gauthier@outlook.com",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "etude-sismique",
    isStepThreeChecked: true,
    isArchitectNeeded: true,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 4,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 3,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 2,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 4,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 5,
    doesNeedPlan: true,
    neededPlans: ["Plan parasismique", "Plan de structure"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 1,
    shouldMake3dRender: true,
    renderCount3d: 3,
    render3D: true,
    clientFirstName: "Maxime",
    clientLastName: "Perrin",
    clientPhone: "+33689012098",
    clientEmail: "maxime.perrin@laposte.net",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "etude-sismique",
    isStepThreeChecked: true,
    isArchitectNeeded: false,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 2,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 5,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 3,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 1,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 4,
    doesNeedPlan: true,
    neededPlans: ["Plan de fondation", "Plan de contreventement"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 2,
    shouldMake3dRender: true,
    renderCount3d: 5,
    render3D: true,
    clientFirstName: "Valérie",
    clientLastName: "Rousseau",
    clientPhone: "+33690123098",
    clientEmail: "valerie.rousseau@free.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "etude-sismique",
    isStepThreeChecked: true,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 3,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 4,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 5,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 2,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 1,
    doesNeedPlan: true,
    neededPlans: ["Plan géotechnique", "Plan sismique"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 3,
    shouldMake3dRender: true,
    renderCount3d: 4,
    render3D: true,
    clientFirstName: "Christophe",
    clientLastName: "Mercier",
    clientPhone: "+33601234098",
    clientEmail: "christophe.mercier@orange.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "aide-conception",
    isStepThreeChecked: true,
    isArchitectNeeded: true,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 5,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 1,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 4,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 3,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 2,
    doesNeedPlan: true,
    neededPlans: ["Plan conception", "Plan esquisse", "Plan avant-projet"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 5,
    shouldMake3dRender: true,
    renderCount3d: 1,
    render3D: true,
    clientFirstName: "Stéphanie",
    clientLastName: "Lambert",
    clientPhone: "+33612345987",
    clientEmail: "stephanie.lambert@hotmail.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "aide-conception",
    isStepThreeChecked: true,
    isArchitectNeeded: false,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 1,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 2,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 1,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 5,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 3,
    doesNeedPlan: true,
    neededPlans: ["Plan préliminaire", "Plan détaillé"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 4,
    shouldMake3dRender: true,
    renderCount3d: 2,
    render3D: true,
    clientFirstName: "Frédéric",
    clientLastName: "Bonnet",
    clientPhone: "+33623456987",
    clientEmail: "frederic.bonnet@sfr.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
  {
    option: "aide-conception",
    isStepThreeChecked: true,
    hasMultipleRealizationsOnSameConstructionPermit: true,
    realizationsOnSameConstructionPermitNumber: 4,
    cerfaFilling: true,
    pluVerification: true,
    rdcPlanVerification: true,
    rdcPlanNumber: 3,
    bbioStudy: true,
    seismicStudy: true,
    expressDelivery: true,
    displayPanel: true,
    hasMultipleRealizationsOnSameDeclaration: true,
    realizationsOnSameDeclarationNumber: 2,
    hasMultipleRealizationsOnSameUrbanismCertificate: true,
    realizationsOnSameUrbanismCertificateNumber: 4,
    hasMultipleRealizationsOnSamePlanRequest: true,
    realizationsOnSamePlanRequestNumber: 5,
    doesNeedPlan: true,
    neededPlans: ["Plan de projet", "Plan d'aménagement"],
    shouldMakeRDCPlan: true,
    rdcPlanCount: 1,
    shouldMake3dRender: true,
    renderCount3d: 3,
    render3D: true,
    clientFirstName: "Caroline",
    clientLastName: "Fournier",
    clientPhone: "+33634567987",
    clientEmail: "caroline.fournier@wanadoo.fr",
    pdfUrl: "/pdf/devis-001 (1).pdf",
  },
];

// Fonction pour traiter les URLs PDF
function processPdfUrls(data) {
  return data.map((item, index) => {
    // Incrémenter l'index de 1 (commence à 1 au lieu de 0)
    const pdfNumber = index + 1;

    // Créer la nouvelle URL sans espaces
    let newPdfUrl;
    if (pdfNumber === 1) {
      newPdfUrl = "/pdf/devis-001.pdf";
    } else {
      newPdfUrl = `/pdf/devis-001(${pdfNumber - 1}).pdf`;
    }

    return {
      ...item,
      pdfUrl: newPdfUrl,
    };
  });
}

// Traiter les données
const processedData = processPdfUrls(data);

// Afficher le résultat
console.log(JSON.stringify(processedData, null, 2));

// Pour copier facilement le résultat
// console.log(JSON.stringify(processedData));
